### ISSUE TITLE
Bug in register_upstream_external_models

### ISSUE THREAD

**Issue by vlieven** [jwills/dbt-duckdb#124]
I have an issue when running a `dbt run --select` statement where external tables are referenced. An invalid upstream location is generated, resulting in the error e.g. `IO Error: No files found that match the pattern "external/root/.parquet"` when running for the config `external_root: "external/root"`.

I've identified the problem in `macros/utils/upstream.sql`, and I'll put up a PR shortly. I'm not sure how to write a test that reproduces this issue though, so I'd appreciate it if you could maybe give me some pointers there. Thanks!

**Comment by Mickychen00** [comment]
Hello. I have set the following in my dbt_project.yml:

```
on-run-start:
- "{{ register_upstream_external_models() }}"
```

However, I'm encountering a runtime error with this configuration in each model:

```
{{ config(materialized='external', location='../../data/data_check/cap_ele.parquet', format='parquet') }}
```

The error message states: 

"IO Error: No files found that match the pattern '../../data/data_check/{{ this.identifier }}.parquet'."

Howerver, if I change {{this.identifier}} to a concrete string name. It works.

What did I do wrong?


#https://github.com/duckdb/dbt-duckdb/issues/227

**Comment by jwills** [comment]
My best guess is that you didn't set the `external_root` property in your profile.yml, which is the root path that dbt-duckdb uses to look for external materializations (it defaults to `.`, the local directory where dbt-duckdb is running)

https://github.com/duckdb/dbt-duckdb/blob/master/dbt/adapters/duckdb/credentials.py#L114

Try setting that field in your profile to an absolute path (possibly based on an environment variable if you're running in multiple different environments) so that the external path materialization will work correctly.

**Comment by Mickychen00** [comment]
Hi. So do you mean I cannot set the external folder as a relative path over the project root?
