### ISSUE TITLE
dbt models that are parquet files

### ISSUE THREAD

**Issue by sryza** [jwills/dbt-duckdb#15]
I haven't thought through this deeply. It might not make sense, it might require changes to dbt, or it might already work? But I wanted to raise it just in case, because it would help me out with something I'm building.

Could we enable configuring dbt-duckdb such that 
```
select
    bla
from {{ ref("orders") }}
```

compiles to

```
select
    bla
from 's3://bucket/orders.parquet'
```
?

**Comment by jwills** [comment]
Yeah, I'm pretty sure that works already! You need to specify the file location as a `source` and use the filepath as an `identifier` ala https://docs.getdbt.com/reference/resource-properties/identifier

I suspect I could make the process for wiring this up a little bit nicer, just LMK how it works for you!

**Comment by jwills** [comment]
Oh actually it might be 1) a `source` with an `identifier` that looks like `"read_parquet('s3://bucket/key')"` modulo https://duckdb.org/docs/guides/import/s3_import

(and of course you would also have to have the AWS S3 creds wired up in the credentials)

**Comment by sryza** [comment]
If I understand correctly, that means dbt sources can be parquet files. Would that approach extend to models?

I.e., in my dream imagination of how this works, when you run a model, it creates a parquet file in S3. If I understand how DuckDB works, this might need to be a two-stage process, where one SQL statement creates the table in DuckDB and then a second one copies it to Parquet. Which might be a little too gnarly?

The advantage of this would be making it easier to use DuckDB in a distributed setting: S3 becomes the coordination point and the database file becomes ephemeral.

**Comment by jwills** [comment]
So you're saying in this execution model that I could fire up multiple DuckDB processes and farm the queries against the Parquet data in S3 (or wherever-- a shared volume could work as well) out to them? That is interesting.

**Comment by sryza** [comment]
Exactly!

**Comment by sgoley** [comment]
Honestly, sounds a lot like what you are looking for @sryza is [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) to be have an adapter for duckdb? 

As far as the development of that goes, it looks like it couldn't be purely "external" in the way that the others adapters for Snowflake or Bigquery operate, but you might be able to make something work through the [COPY](https://duckdb.org/docs/sql/statements/copy) api since that supports external load of parquet files from a remote storage.

That would be my starting point.

**Comment by jwills** [comment]
I started experimenting with this idea over here: https://github.com/jwills/dbt-duckdb/compare/jwills_file_based_dbs?expand=1

This will work in the sense that if you specify a `database` for your `source`s that looks like a path (in some currently ill-defined sense), dbt will render references to that `source` as a path, and if you have the S3 stuff setup and are on Linux, it should work to read data in CSV/Parquet files on S3 or the local filesystem. Still a bunch of stuff I would need to do to make this real, but the germ of the idea is there.

The `ref` side of things is trickier in that dbt normally expects to be able to manipulate the resulting object in the DB as though it were some kind of relation (usually either a view or a table) although there are exceptions for some kinds of materializations (ephemeral models); I think the safest/cleanest way to handle things on the output side would be to run a [post-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) that would do the `COPY {{ this }} TO '/path/to/parquet/{{ this }}.parquet'` after the model was created.

**Comment by AlexanderVR** [comment]
I'd been playing around with this idea for a few weekends, but had forgotten about it for a bit. Since others appear interested, I've cleaned it up and posted to https://github.com/AlexanderVR/dbt-parquet

Still needs a little bit of work to hook up to S3 instead of local files. Obviously, things like views and incremental models don't make immediate sense. Would love to hook in python with `dbt` 1.3, with the similar spirit of https://github.com/dbt-labs/dbt-core/discussions/5261#discussioncomment-2777498

**Comment by nialloriordan** [comment]
I thought the point of DuckDB was to be a local data warehouse and avoid sending data to and from s3? If you just want to back up your data to s3, then that’s a separate task which you could run on a schedule and then query your data in s3 using another service such as AWS Athena?

**Comment by sryza** [comment]
@AlexanderVR this is cool

**Comment by tomsej** [comment]
I was thinking about the possible solutions for this too. Think this is only viable for `table` materializations:
  - incrementals and snapshots are not possible, since `parquet` does not support updates (unlike iceberg or delta).
  - views are database objects so does not make sense
  - seeds are already outside the database
I was thinking about introducing a new type of materialization (or adding some extra parameters to the current), e.g. `parquet`. With that, the last steps (usually something like `CREATE TABLE ...`) of the table materializations would be instead `COPY (SELECT ...) TO '<location parameter>.parquet'` and `CREATE VIEW AS SELECT FROM <location parameter>.parquet` so the `table` would not be actual table but a view on the `parquet`. Think this is similar to what @AlexanderVR is doing. Any thoughts?

**Comment by jwills** [comment]
I wired up a version of this idea here: https://github.com/jwills/dbt-duckdb/compare/jwills_file_based_dbs?expand=1

I got things working, but I didn't feel great about it. My "idea" was to take advantage of the fact that the `database` config parameter is a no-op for DuckDB so that if you specify a path instead of the default (`main`), I do some hacks to treat any models under that database + schema path as parquet/CSV files-- including when you `ref` them in other models (so for example a ref'd model that uses the `parquet` materialization will be rendered when it is queried as `<database>/<schema>/<model>.parquet` instead of `database.schema.model`.

I like what @tomsej is saying better tho (i.e., the `parquet` materialization acts like a `view` over a parquet file, where the location of where the parquet file(s) should be materialized is specified...somewhere?), b/c it keeps the metadata catalog where it belongs-- inside of DuckDB, and not externally managed via dbt-duckdb + the filesystem. Radek's approach means that we don't have to jump through a whole bunch of hoops inside of the `DuckDBAdapter` and `DuckDBRelation` classes (as I do in the above branch) to render the relation differently when it's a parquet/csv file instead of a regular table/view. To me, that makes the `parquet` materialization into some syntactic sugar that is equivalent to materializing a view model that has a post-hook which does the `COPY (SELECT * FROM {{ this }}) TO '/path/to/output.parquet'` for us, and I would be 👍 for such a materialization (and maybe a `csv` one that did the same sort of thing if we were so inclined?)

**Comment by tomsej** [comment]
@jwills, @sryza I just created a new branch https://github.com/jwills/dbt-duckdb/pull/33 that contains a new type of materialization `external_table`. It allows you to dump data into `csv` or `parquet` and it creates a view on this dump. As I wrote, it currently supports only `csv` and `dbt` but I would like to implement `iceberg` and `delta` in the future, especially for `incremental` models.

If you want to give it a spin, all you need to do is to install it:

```
git+https://github.com/jwills/dbt-duckdb.git@external_table#egg=dbt-duckdb
```

and edit the configuration, like this:

```
{{
    config(
        materialized='external_table',
        location='test.parquet',
        format='parquet'
    )
}}
```
or
```
{{
    config(
        materialized='external_table',
        location='test.csv',
        format='csv',
        delimiter=';'
    )
}}
```
It should also work with `httpfs` (S3) and even Python models. I will really appreciate any suggestions or comments. Thank you!

**Comment by tomsej** [comment]
I am closing this issue in favour of #19, which is solving the same problem, but it goes more into the detail. If you disagree, feel free to reopen.
