### ISSUE TITLE
Support for duckdb 0.6.*

### ISSUE THREAD

**Issue by ergodiclife** [jwills/dbt-duckdb#59]
Hi,

`duckdb` 0.6.0 has been [released](https://duckdb.org/2022/11/14/announcing-duckdb-060.html) recently - it would be great if `dbt-duckdb` could support the new version.

Thanks!

**Comment by jwills** [comment]
@tomsej feels like with the release cadence of the DuckDB team being roughly the same as the dbt team (every 3 months or so per major release, although 6 weeks off from the dbt release schedule) we need to allow folks to use either the current release or the upcoming one with dbt-duckdb; what's the best way to represent that in the `setup.py` file? Just the `>=` condition, or do we specify both supported versions (the current one and the next one) explicitly?

**Comment by tomsej** [comment]
Yeah this is a good point. I would probably unpin the duckdb dependency (change it to >= instead of ~=). So it would always install the latest version of duckdb. But I would keep dbt pinned b/c we have version number dependent on dbt. Means that we need to release the new version only if dbt release major one

**Comment by tomsej** [comment]
Sorry I thought that I kept duckdb unpinned.

**Comment by jwills** [comment]
no worries, I missed it as well; we can fix it and do a new release
