### ISSUE TITLE
Changing seeds columns fails

### ISSUE THREAD

**Issue by mk-oliver-s** [jwills/dbt-duckdb#91]
If I have seeds that look like this

```csv
id,value
1,'hello'
2,'world'
```

and then change to look like this

```csv
id,status
1,'hello'
2,'world'
```

then I get 

```logs
00:40:48  Runtime Error in seed so2_status_codes (seeds/status_codes.csv)
00:40:48    Binder Error: Table "so2_status_codes" does not have a column with name "status"
```

And the table must be manually deleted in order to work around.

**Comment by jwills** [comment]
well that sucks, I'm sure I can repro that pretty easily... 👀

**Comment by jwills** [comment]
Yep, easy to repro, but it looks like we match the behavior of other dbt adapters based on my reading of the code here: https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/seeds/helpers.sql#L33

If you run `dbt seed --full-refresh`, the error goes away; the issue is that a seed table is only `truncate`'d by default, not dropped entirely, and it seems like that applies to any of the adapters.

**Comment by kyleries** [comment]
Indeed, just confirming what @jwills read in the source - the [Docs](https://docs.getdbt.com/faqs/seeds/full-refresh-seed) verify that behavior as designed.

**Comment by mk-oliver-s** [comment]
Ahh ok, cool!

Thanks for quick response and maintaining this project!! :D
